//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class BaseSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static BaseSettings defaultInstance = ((BaseSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BaseSettings())));
        
        public static BaseSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
