//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccessRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.Profile[] FriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.Product[] GamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MainImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccessRight {
            get {
                return this.AccessRightField;
            }
            set {
                if ((this.AccessRightField.Equals(value) != true)) {
                    this.AccessRightField = value;
                    this.RaisePropertyChanged("AccessRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.Service.Profile[] Friends {
            get {
                return this.FriendsField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendsField, value) != true)) {
                    this.FriendsField = value;
                    this.RaisePropertyChanged("Friends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.Service.Product[] Games {
            get {
                return this.GamesField;
            }
            set {
                if ((object.ReferenceEquals(this.GamesField, value) != true)) {
                    this.GamesField = value;
                    this.RaisePropertyChanged("Games");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MainImage {
            get {
                return this.MainImageField;
            }
            set {
                if ((object.ReferenceEquals(this.MainImageField, value) != true)) {
                    this.MainImageField = value;
                    this.RaisePropertyChanged("MainImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeveloperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GameGenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MainImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MinGameSysReqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RecGameSysReqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RetailPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WholesalePriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Developer {
            get {
                return this.DeveloperField;
            }
            set {
                if ((object.ReferenceEquals(this.DeveloperField, value) != true)) {
                    this.DeveloperField = value;
                    this.RaisePropertyChanged("Developer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] GameGenre {
            get {
                return this.GameGenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GameGenreField, value) != true)) {
                    this.GameGenreField = value;
                    this.RaisePropertyChanged("GameGenre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MainImage {
            get {
                return this.MainImageField;
            }
            set {
                if ((object.ReferenceEquals(this.MainImageField, value) != true)) {
                    this.MainImageField = value;
                    this.RaisePropertyChanged("MainImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] MinGameSysReq {
            get {
                return this.MinGameSysReqField;
            }
            set {
                if ((object.ReferenceEquals(this.MinGameSysReqField, value) != true)) {
                    this.MinGameSysReqField = value;
                    this.RaisePropertyChanged("MinGameSysReq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] RecGameSysReq {
            get {
                return this.RecGameSysReqField;
            }
            set {
                if ((object.ReferenceEquals(this.RecGameSysReqField, value) != true)) {
                    this.RecGameSysReqField = value;
                    this.RaisePropertyChanged("RecGameSysReq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RetailPrice {
            get {
                return this.RetailPriceField;
            }
            set {
                if ((this.RetailPriceField.Equals(value) != true)) {
                    this.RetailPriceField = value;
                    this.RaisePropertyChanged("RetailPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WholesalePrice {
            get {
                return this.WholesalePriceField;
            }
            set {
                if ((this.WholesalePriceField.Equals(value) != true)) {
                    this.WholesalePriceField = value;
                    this.RaisePropertyChanged("WholesalePrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserMessage", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class UserMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDReceiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDSenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDReceiver {
            get {
                return this.IDReceiverField;
            }
            set {
                if ((this.IDReceiverField.Equals(value) != true)) {
                    this.IDReceiverField = value;
                    this.RaisePropertyChanged("IDReceiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDSender {
            get {
                return this.IDSenderField;
            }
            set {
                if ((this.IDSenderField.Equals(value) != true)) {
                    this.IDSenderField = value;
                    this.RaisePropertyChanged("IDSender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isRead {
            get {
                return this.isReadField;
            }
            set {
                if ((this.isReadField.Equals(value) != true)) {
                    this.isReadField = value;
                    this.RaisePropertyChanged("isRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Comment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProduct {
            get {
                return this.idProductField;
            }
            set {
                if ((this.idProductField.Equals(value) != true)) {
                    this.idProductField = value;
                    this.RaisePropertyChanged("idProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUser {
            get {
                return this.idUserField;
            }
            set {
                if ((this.idUserField.Equals(value) != true)) {
                    this.idUserField = value;
                    this.RaisePropertyChanged("idUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IWCFService", CallbackContract=typeof(Client.Service.IWCFServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IWCFService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/Connect")]
        void Connect(string Login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/Connect")]
        System.Threading.Tasks.Task ConnectAsync(string Login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ActiveProfile", ReplyAction="http://tempuri.org/IWCFService/ActiveProfileResponse")]
        Client.Service.Profile ActiveProfile(string Login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ActiveProfile", ReplyAction="http://tempuri.org/IWCFService/ActiveProfileResponse")]
        System.Threading.Tasks.Task<Client.Service.Profile> ActiveProfileAsync(string Login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/Disconnect")]
        void Disconnect(int Id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetProductTable", ReplyAction="http://tempuri.org/IWCFService/GetProductTableResponse")]
        Client.Service.Product[] GetProductTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetProductTable", ReplyAction="http://tempuri.org/IWCFService/GetProductTableResponse")]
        System.Threading.Tasks.Task<Client.Service.Product[]> GetProductTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/Register", ReplyAction="http://tempuri.org/IWCFService/RegisterResponse")]
        void Register(Client.Service.Profile profile, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/Register", ReplyAction="http://tempuri.org/IWCFService/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(Client.Service.Profile profile, string Password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/AddFriend")]
        void AddFriend(int id, int idFriend);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/AddFriend")]
        System.Threading.Tasks.Task AddFriendAsync(int id, int idFriend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetChat", ReplyAction="http://tempuri.org/IWCFService/GetChatResponse")]
        Client.Service.UserMessage[] GetChat(int idMain, int idComrade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetChat", ReplyAction="http://tempuri.org/IWCFService/GetChatResponse")]
        System.Threading.Tasks.Task<Client.Service.UserMessage[]> GetChatAsync(int idMain, int idComrade);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/BuyProduct")]
        void BuyProduct(int[] Cart, int idProfile);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/BuyProduct")]
        System.Threading.Tasks.Task BuyProductAsync(int[] Cart, int idProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/BuyProductWholesale", ReplyAction="http://tempuri.org/IWCFService/BuyProductWholesaleResponse")]
        Client.Service.Product[] BuyProductWholesale(System.Tuple<int, int>[] Cart, int idProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/BuyProductWholesale", ReplyAction="http://tempuri.org/IWCFService/BuyProductWholesaleResponse")]
        System.Threading.Tasks.Task<Client.Service.Product[]> BuyProductWholesaleAsync(System.Tuple<int, int>[] Cart, int idProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/CheckBlacklist", ReplyAction="http://tempuri.org/IWCFService/CheckBlacklistResponse")]
        bool CheckBlacklist(int IdMainUser, int IdSeconUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/CheckBlacklist", ReplyAction="http://tempuri.org/IWCFService/CheckBlacklistResponse")]
        System.Threading.Tasks.Task<bool> CheckBlacklistAsync(int IdMainUser, int IdSeconUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/AddModerationProduct")]
        void AddModerationProduct(Client.Service.Product product, byte[][] Images);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/AddModerationProduct")]
        System.Threading.Tasks.Task AddModerationProductAsync(Client.Service.Product product, byte[][] Images);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/DeleteAccount")]
        void DeleteAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/DeleteAccount")]
        System.Threading.Tasks.Task DeleteAccountAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/AddToBlacklist")]
        void AddToBlacklist(int id, int idUserToBlacklist);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/AddToBlacklist")]
        System.Threading.Tasks.Task AddToBlacklistAsync(int id, int idUserToBlacklist);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/DeleteFriendReqest")]
        void DeleteFriendReqest(int id, int idRequest);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/DeleteFriendReqest")]
        System.Threading.Tasks.Task DeleteFriendReqestAsync(int id, int idRequest);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/DeleteFriend")]
        void DeleteFriend(int id, int idFriend);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/DeleteFriend")]
        System.Threading.Tasks.Task DeleteFriendAsync(int id, int idFriend);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/RemoveFromBlacklist")]
        void RemoveFromBlacklist(int id, int idUserInBlacklist);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/RemoveFromBlacklist")]
        System.Threading.Tasks.Task RemoveFromBlacklistAsync(int id, int idUserInBlacklist);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/SendMsg")]
        void SendMsg(Client.Service.UserMessage msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/SendMsg")]
        System.Threading.Tasks.Task SendMsgAsync(Client.Service.UserMessage msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/SaveCart")]
        void SaveCart(int idUser, Client.Service.Product[] Cart);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/SaveCart")]
        System.Threading.Tasks.Task SaveCartAsync(int idUser, Client.Service.Product[] Cart);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/SendFriendRequest")]
        void SendFriendRequest(int idSender, int idReceiver);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/SendFriendRequest")]
        System.Threading.Tasks.Task SendFriendRequestAsync(int idSender, int idReceiver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/CheckProfile", ReplyAction="http://tempuri.org/IWCFService/CheckProfileResponse")]
        Client.Service.Profile CheckProfile(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/CheckProfile", ReplyAction="http://tempuri.org/IWCFService/CheckProfileResponse")]
        System.Threading.Tasks.Task<Client.Service.Profile> CheckProfileAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetAllUsers", ReplyAction="http://tempuri.org/IWCFService/GetAllUsersResponse")]
        Client.Service.Profile[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetAllUsers", ReplyAction="http://tempuri.org/IWCFService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<Client.Service.Profile[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetNewMessages", ReplyAction="http://tempuri.org/IWCFService/GetNewMessagesResponse")]
        Client.Service.UserMessage[] GetNewMessages(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetNewMessages", ReplyAction="http://tempuri.org/IWCFService/GetNewMessagesResponse")]
        System.Threading.Tasks.Task<Client.Service.UserMessage[]> GetNewMessagesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetFriendRequests", ReplyAction="http://tempuri.org/IWCFService/GetFriendRequestsResponse")]
        Client.Service.Profile[] GetFriendRequests(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetFriendRequests", ReplyAction="http://tempuri.org/IWCFService/GetFriendRequestsResponse")]
        System.Threading.Tasks.Task<Client.Service.Profile[]> GetFriendRequestsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetUserGames", ReplyAction="http://tempuri.org/IWCFService/GetUserGamesResponse")]
        Client.Service.Product[] GetUserGames(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetUserGames", ReplyAction="http://tempuri.org/IWCFService/GetUserGamesResponse")]
        System.Threading.Tasks.Task<Client.Service.Product[]> GetUserGamesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/CheckActiveProfile", ReplyAction="http://tempuri.org/IWCFService/CheckActiveProfileResponse")]
        Client.Service.Profile CheckActiveProfile(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/CheckActiveProfile", ReplyAction="http://tempuri.org/IWCFService/CheckActiveProfileResponse")]
        System.Threading.Tasks.Task<Client.Service.Profile> CheckActiveProfileAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetProfileByFilter", ReplyAction="http://tempuri.org/IWCFService/GetProfileByFilterResponse")]
        Client.Service.Profile[] GetProfileByFilter(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetProfileByFilter", ReplyAction="http://tempuri.org/IWCFService/GetProfileByFilterResponse")]
        System.Threading.Tasks.Task<Client.Service.Profile[]> GetProfileByFilterAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetGameImages", ReplyAction="http://tempuri.org/IWCFService/GetGameImagesResponse")]
        byte[][] GetGameImages(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetGameImages", ReplyAction="http://tempuri.org/IWCFService/GetGameImagesResponse")]
        System.Threading.Tasks.Task<byte[][]> GetGameImagesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/AddComment")]
        void AddComment(Client.Service.Comment comment);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/AddComment")]
        System.Threading.Tasks.Task AddCommentAsync(Client.Service.Comment comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetAllGameComments", ReplyAction="http://tempuri.org/IWCFService/GetAllGameCommentsResponse")]
        System.Tuple<Client.Service.Comment, Client.Service.Profile>[] GetAllGameComments(int idGame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetAllGameComments", ReplyAction="http://tempuri.org/IWCFService/GetAllGameCommentsResponse")]
        System.Threading.Tasks.Task<System.Tuple<Client.Service.Comment, Client.Service.Profile>[]> GetAllGameCommentsAsync(int idGame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetEasyProfile", ReplyAction="http://tempuri.org/IWCFService/GetEasyProfileResponse")]
        Client.Service.Profile GetEasyProfile(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetEasyProfile", ReplyAction="http://tempuri.org/IWCFService/GetEasyProfileResponse")]
        System.Threading.Tasks.Task<Client.Service.Profile> GetEasyProfileAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetWayToGame", ReplyAction="http://tempuri.org/IWCFService/GetWayToGameResponse")]
        string GetWayToGame(int idUser, int idGame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetWayToGame", ReplyAction="http://tempuri.org/IWCFService/GetWayToGameResponse")]
        System.Threading.Tasks.Task<string> GetWayToGameAsync(int idUser, int idGame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/CheckMail", ReplyAction="http://tempuri.org/IWCFService/CheckMailResponse")]
        string CheckMail(string Mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/CheckMail", ReplyAction="http://tempuri.org/IWCFService/CheckMailResponse")]
        System.Threading.Tasks.Task<string> CheckMailAsync(string Mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ResetPassword", ReplyAction="http://tempuri.org/IWCFService/ResetPasswordResponse")]
        string ResetPassword(string Mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ResetPassword", ReplyAction="http://tempuri.org/IWCFService/ResetPasswordResponse")]
        System.Threading.Tasks.Task<string> ResetPasswordAsync(string Mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetModerationProduct", ReplyAction="http://tempuri.org/IWCFService/GetModerationProductResponse")]
        Client.Service.Product[] GetModerationProduct(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetModerationProduct", ReplyAction="http://tempuri.org/IWCFService/GetModerationProductResponse")]
        System.Threading.Tasks.Task<Client.Service.Product[]> GetModerationProductAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/ChangeModerationStatus")]
        void ChangeModerationStatus(int idUser, int idModerationProduct, bool result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/ChangeModerationStatus")]
        System.Threading.Tasks.Task ChangeModerationStatusAsync(int idUser, int idModerationProduct, bool result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/changePassword", ReplyAction="http://tempuri.org/IWCFService/changePasswordResponse")]
        void changePassword(int idUser, string password, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/changePassword", ReplyAction="http://tempuri.org/IWCFService/changePasswordResponse")]
        System.Threading.Tasks.Task changePasswordAsync(int idUser, string password, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/ChangeProfileInformation")]
        void ChangeProfileInformation(Client.Service.Profile profile);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/ChangeProfileInformation")]
        System.Threading.Tasks.Task ChangeProfileInformationAsync(Client.Service.Profile profile);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/DeleteComment")]
        void DeleteComment(int idUser, int idProduct);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/DeleteComment")]
        System.Threading.Tasks.Task DeleteCommentAsync(int idUser, int idProduct);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/changeProfileImage")]
        void changeProfileImage(int idUser, byte[] MainImage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/changeProfileImage")]
        System.Threading.Tasks.Task changeProfileImageAsync(int idUser, byte[] MainImage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/SetMessageRead")]
        void SetMessageRead(int id, int idChatedUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/SetMessageRead")]
        System.Threading.Tasks.Task SetMessageReadAsync(int id, int idChatedUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/ActivateLicenseKey")]
        void ActivateLicenseKey(int id, string Key);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/ActivateLicenseKey")]
        System.Threading.Tasks.Task ActivateLicenseKeyAsync(int id, string Key);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (resetPassword) сообщения resetPassword не соответствует значению по умолчанию (resetPassword1).
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/resetPassword")]
        void resetPassword1(Client.Service.resetPassword request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/resetPassword")]
        System.Threading.Tasks.Task resetPassword1Async(Client.Service.resetPassword request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetProductByFilter", ReplyAction="http://tempuri.org/IWCFService/GetProductByFilterResponse")]
        Client.Service.Product[] GetProductByFilter(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetProductByFilter", ReplyAction="http://tempuri.org/IWCFService/GetProductByFilterResponse")]
        System.Threading.Tasks.Task<Client.Service.Product[]> GetProductByFilterAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/ChangeAccessRight")]
        void ChangeAccessRight(int idUser, int AccessRight);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/ChangeAccessRight")]
        System.Threading.Tasks.Task ChangeAccessRightAsync(int idUser, int AccessRight);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/ChangeComment")]
        void ChangeComment(Client.Service.Comment comment);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/ChangeComment")]
        System.Threading.Tasks.Task ChangeCommentAsync(Client.Service.Comment comment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/FriendOffline")]
        void FriendOffline(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/GetMessage")]
        void GetMessage(Client.Service.UserMessage msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/ConnectionFromAnotherDevice")]
        void ConnectionFromAnotherDevice();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/GetFriendRequest")]
        void GetFriendRequest(Client.Service.Profile pr);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/FriendOnline")]
        void FriendOnline(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/AcceptFriendRequest")]
        void AcceptFriendRequest(Client.Service.Profile pr);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resetPassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class resetPassword {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string newPassword;
        
        public resetPassword() {
        }
        
        public resetPassword(int idUser, string newPassword) {
            this.idUser = idUser;
            this.newPassword = newPassword;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceChannel : Client.Service.IWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceClient : System.ServiceModel.DuplexClientBase<Client.Service.IWCFService>, Client.Service.IWCFService {
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Connect(string Login, string Password) {
            base.Channel.Connect(Login, Password);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(string Login, string Password) {
            return base.Channel.ConnectAsync(Login, Password);
        }
        
        public Client.Service.Profile ActiveProfile(string Login, string Password) {
            return base.Channel.ActiveProfile(Login, Password);
        }
        
        public System.Threading.Tasks.Task<Client.Service.Profile> ActiveProfileAsync(string Login, string Password) {
            return base.Channel.ActiveProfileAsync(Login, Password);
        }
        
        public void Disconnect(int Id) {
            base.Channel.Disconnect(Id);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(int Id) {
            return base.Channel.DisconnectAsync(Id);
        }
        
        public Client.Service.Product[] GetProductTable() {
            return base.Channel.GetProductTable();
        }
        
        public System.Threading.Tasks.Task<Client.Service.Product[]> GetProductTableAsync() {
            return base.Channel.GetProductTableAsync();
        }
        
        public void Register(Client.Service.Profile profile, string Password) {
            base.Channel.Register(profile, Password);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(Client.Service.Profile profile, string Password) {
            return base.Channel.RegisterAsync(profile, Password);
        }
        
        public void AddFriend(int id, int idFriend) {
            base.Channel.AddFriend(id, idFriend);
        }
        
        public System.Threading.Tasks.Task AddFriendAsync(int id, int idFriend) {
            return base.Channel.AddFriendAsync(id, idFriend);
        }
        
        public Client.Service.UserMessage[] GetChat(int idMain, int idComrade) {
            return base.Channel.GetChat(idMain, idComrade);
        }
        
        public System.Threading.Tasks.Task<Client.Service.UserMessage[]> GetChatAsync(int idMain, int idComrade) {
            return base.Channel.GetChatAsync(idMain, idComrade);
        }
        
        public void BuyProduct(int[] Cart, int idProfile) {
            base.Channel.BuyProduct(Cart, idProfile);
        }
        
        public System.Threading.Tasks.Task BuyProductAsync(int[] Cart, int idProfile) {
            return base.Channel.BuyProductAsync(Cart, idProfile);
        }
        
        public Client.Service.Product[] BuyProductWholesale(System.Tuple<int, int>[] Cart, int idProfile) {
            return base.Channel.BuyProductWholesale(Cart, idProfile);
        }
        
        public System.Threading.Tasks.Task<Client.Service.Product[]> BuyProductWholesaleAsync(System.Tuple<int, int>[] Cart, int idProfile) {
            return base.Channel.BuyProductWholesaleAsync(Cart, idProfile);
        }
        
        public bool CheckBlacklist(int IdMainUser, int IdSeconUser) {
            return base.Channel.CheckBlacklist(IdMainUser, IdSeconUser);
        }
        
        public System.Threading.Tasks.Task<bool> CheckBlacklistAsync(int IdMainUser, int IdSeconUser) {
            return base.Channel.CheckBlacklistAsync(IdMainUser, IdSeconUser);
        }
        
        public void AddModerationProduct(Client.Service.Product product, byte[][] Images) {
            base.Channel.AddModerationProduct(product, Images);
        }
        
        public System.Threading.Tasks.Task AddModerationProductAsync(Client.Service.Product product, byte[][] Images) {
            return base.Channel.AddModerationProductAsync(product, Images);
        }
        
        public void DeleteAccount(int id) {
            base.Channel.DeleteAccount(id);
        }
        
        public System.Threading.Tasks.Task DeleteAccountAsync(int id) {
            return base.Channel.DeleteAccountAsync(id);
        }
        
        public void AddToBlacklist(int id, int idUserToBlacklist) {
            base.Channel.AddToBlacklist(id, idUserToBlacklist);
        }
        
        public System.Threading.Tasks.Task AddToBlacklistAsync(int id, int idUserToBlacklist) {
            return base.Channel.AddToBlacklistAsync(id, idUserToBlacklist);
        }
        
        public void DeleteFriendReqest(int id, int idRequest) {
            base.Channel.DeleteFriendReqest(id, idRequest);
        }
        
        public System.Threading.Tasks.Task DeleteFriendReqestAsync(int id, int idRequest) {
            return base.Channel.DeleteFriendReqestAsync(id, idRequest);
        }
        
        public void DeleteFriend(int id, int idFriend) {
            base.Channel.DeleteFriend(id, idFriend);
        }
        
        public System.Threading.Tasks.Task DeleteFriendAsync(int id, int idFriend) {
            return base.Channel.DeleteFriendAsync(id, idFriend);
        }
        
        public void RemoveFromBlacklist(int id, int idUserInBlacklist) {
            base.Channel.RemoveFromBlacklist(id, idUserInBlacklist);
        }
        
        public System.Threading.Tasks.Task RemoveFromBlacklistAsync(int id, int idUserInBlacklist) {
            return base.Channel.RemoveFromBlacklistAsync(id, idUserInBlacklist);
        }
        
        public void SendMsg(Client.Service.UserMessage msg) {
            base.Channel.SendMsg(msg);
        }
        
        public System.Threading.Tasks.Task SendMsgAsync(Client.Service.UserMessage msg) {
            return base.Channel.SendMsgAsync(msg);
        }
        
        public void SaveCart(int idUser, Client.Service.Product[] Cart) {
            base.Channel.SaveCart(idUser, Cart);
        }
        
        public System.Threading.Tasks.Task SaveCartAsync(int idUser, Client.Service.Product[] Cart) {
            return base.Channel.SaveCartAsync(idUser, Cart);
        }
        
        public void SendFriendRequest(int idSender, int idReceiver) {
            base.Channel.SendFriendRequest(idSender, idReceiver);
        }
        
        public System.Threading.Tasks.Task SendFriendRequestAsync(int idSender, int idReceiver) {
            return base.Channel.SendFriendRequestAsync(idSender, idReceiver);
        }
        
        public Client.Service.Profile CheckProfile(int idUser) {
            return base.Channel.CheckProfile(idUser);
        }
        
        public System.Threading.Tasks.Task<Client.Service.Profile> CheckProfileAsync(int idUser) {
            return base.Channel.CheckProfileAsync(idUser);
        }
        
        public Client.Service.Profile[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<Client.Service.Profile[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public Client.Service.UserMessage[] GetNewMessages(int id) {
            return base.Channel.GetNewMessages(id);
        }
        
        public System.Threading.Tasks.Task<Client.Service.UserMessage[]> GetNewMessagesAsync(int id) {
            return base.Channel.GetNewMessagesAsync(id);
        }
        
        public Client.Service.Profile[] GetFriendRequests(int id) {
            return base.Channel.GetFriendRequests(id);
        }
        
        public System.Threading.Tasks.Task<Client.Service.Profile[]> GetFriendRequestsAsync(int id) {
            return base.Channel.GetFriendRequestsAsync(id);
        }
        
        public Client.Service.Product[] GetUserGames(int id) {
            return base.Channel.GetUserGames(id);
        }
        
        public System.Threading.Tasks.Task<Client.Service.Product[]> GetUserGamesAsync(int id) {
            return base.Channel.GetUserGamesAsync(id);
        }
        
        public Client.Service.Profile CheckActiveProfile(int idUser) {
            return base.Channel.CheckActiveProfile(idUser);
        }
        
        public System.Threading.Tasks.Task<Client.Service.Profile> CheckActiveProfileAsync(int idUser) {
            return base.Channel.CheckActiveProfileAsync(idUser);
        }
        
        public Client.Service.Profile[] GetProfileByFilter(string filter) {
            return base.Channel.GetProfileByFilter(filter);
        }
        
        public System.Threading.Tasks.Task<Client.Service.Profile[]> GetProfileByFilterAsync(string filter) {
            return base.Channel.GetProfileByFilterAsync(filter);
        }
        
        public byte[][] GetGameImages(int id) {
            return base.Channel.GetGameImages(id);
        }
        
        public System.Threading.Tasks.Task<byte[][]> GetGameImagesAsync(int id) {
            return base.Channel.GetGameImagesAsync(id);
        }
        
        public void AddComment(Client.Service.Comment comment) {
            base.Channel.AddComment(comment);
        }
        
        public System.Threading.Tasks.Task AddCommentAsync(Client.Service.Comment comment) {
            return base.Channel.AddCommentAsync(comment);
        }
        
        public System.Tuple<Client.Service.Comment, Client.Service.Profile>[] GetAllGameComments(int idGame) {
            return base.Channel.GetAllGameComments(idGame);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<Client.Service.Comment, Client.Service.Profile>[]> GetAllGameCommentsAsync(int idGame) {
            return base.Channel.GetAllGameCommentsAsync(idGame);
        }
        
        public Client.Service.Profile GetEasyProfile(int id) {
            return base.Channel.GetEasyProfile(id);
        }
        
        public System.Threading.Tasks.Task<Client.Service.Profile> GetEasyProfileAsync(int id) {
            return base.Channel.GetEasyProfileAsync(id);
        }
        
        public string GetWayToGame(int idUser, int idGame) {
            return base.Channel.GetWayToGame(idUser, idGame);
        }
        
        public System.Threading.Tasks.Task<string> GetWayToGameAsync(int idUser, int idGame) {
            return base.Channel.GetWayToGameAsync(idUser, idGame);
        }
        
        public string CheckMail(string Mail) {
            return base.Channel.CheckMail(Mail);
        }
        
        public System.Threading.Tasks.Task<string> CheckMailAsync(string Mail) {
            return base.Channel.CheckMailAsync(Mail);
        }
        
        public string ResetPassword(string Mail) {
            return base.Channel.ResetPassword(Mail);
        }
        
        public System.Threading.Tasks.Task<string> ResetPasswordAsync(string Mail) {
            return base.Channel.ResetPasswordAsync(Mail);
        }
        
        public Client.Service.Product[] GetModerationProduct(int idUser) {
            return base.Channel.GetModerationProduct(idUser);
        }
        
        public System.Threading.Tasks.Task<Client.Service.Product[]> GetModerationProductAsync(int idUser) {
            return base.Channel.GetModerationProductAsync(idUser);
        }
        
        public void ChangeModerationStatus(int idUser, int idModerationProduct, bool result) {
            base.Channel.ChangeModerationStatus(idUser, idModerationProduct, result);
        }
        
        public System.Threading.Tasks.Task ChangeModerationStatusAsync(int idUser, int idModerationProduct, bool result) {
            return base.Channel.ChangeModerationStatusAsync(idUser, idModerationProduct, result);
        }
        
        public void changePassword(int idUser, string password, string newPassword) {
            base.Channel.changePassword(idUser, password, newPassword);
        }
        
        public System.Threading.Tasks.Task changePasswordAsync(int idUser, string password, string newPassword) {
            return base.Channel.changePasswordAsync(idUser, password, newPassword);
        }
        
        public void ChangeProfileInformation(Client.Service.Profile profile) {
            base.Channel.ChangeProfileInformation(profile);
        }
        
        public System.Threading.Tasks.Task ChangeProfileInformationAsync(Client.Service.Profile profile) {
            return base.Channel.ChangeProfileInformationAsync(profile);
        }
        
        public void DeleteComment(int idUser, int idProduct) {
            base.Channel.DeleteComment(idUser, idProduct);
        }
        
        public System.Threading.Tasks.Task DeleteCommentAsync(int idUser, int idProduct) {
            return base.Channel.DeleteCommentAsync(idUser, idProduct);
        }
        
        public void changeProfileImage(int idUser, byte[] MainImage) {
            base.Channel.changeProfileImage(idUser, MainImage);
        }
        
        public System.Threading.Tasks.Task changeProfileImageAsync(int idUser, byte[] MainImage) {
            return base.Channel.changeProfileImageAsync(idUser, MainImage);
        }
        
        public void SetMessageRead(int id, int idChatedUser) {
            base.Channel.SetMessageRead(id, idChatedUser);
        }
        
        public System.Threading.Tasks.Task SetMessageReadAsync(int id, int idChatedUser) {
            return base.Channel.SetMessageReadAsync(id, idChatedUser);
        }
        
        public void ActivateLicenseKey(int id, string Key) {
            base.Channel.ActivateLicenseKey(id, Key);
        }
        
        public System.Threading.Tasks.Task ActivateLicenseKeyAsync(int id, string Key) {
            return base.Channel.ActivateLicenseKeyAsync(id, Key);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Client.Service.IWCFService.resetPassword1(Client.Service.resetPassword request) {
            base.Channel.resetPassword1(request);
        }
        
        public void resetPassword1(int idUser, string newPassword) {
            Client.Service.resetPassword inValue = new Client.Service.resetPassword();
            inValue.idUser = idUser;
            inValue.newPassword = newPassword;
            ((Client.Service.IWCFService)(this)).resetPassword1(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Client.Service.IWCFService.resetPassword1Async(Client.Service.resetPassword request) {
            return base.Channel.resetPassword1Async(request);
        }
        
        public System.Threading.Tasks.Task resetPassword1Async(int idUser, string newPassword) {
            Client.Service.resetPassword inValue = new Client.Service.resetPassword();
            inValue.idUser = idUser;
            inValue.newPassword = newPassword;
            return ((Client.Service.IWCFService)(this)).resetPassword1Async(inValue);
        }
        
        public Client.Service.Product[] GetProductByFilter(string filter) {
            return base.Channel.GetProductByFilter(filter);
        }
        
        public System.Threading.Tasks.Task<Client.Service.Product[]> GetProductByFilterAsync(string filter) {
            return base.Channel.GetProductByFilterAsync(filter);
        }
        
        public void ChangeAccessRight(int idUser, int AccessRight) {
            base.Channel.ChangeAccessRight(idUser, AccessRight);
        }
        
        public System.Threading.Tasks.Task ChangeAccessRightAsync(int idUser, int AccessRight) {
            return base.Channel.ChangeAccessRightAsync(idUser, AccessRight);
        }
        
        public void ChangeComment(Client.Service.Comment comment) {
            base.Channel.ChangeComment(comment);
        }
        
        public System.Threading.Tasks.Task ChangeCommentAsync(Client.Service.Comment comment) {
            return base.Channel.ChangeCommentAsync(comment);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IDownloadService")]
    public interface IDownloadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadService/DownloadProduct", ReplyAction="http://tempuri.org/IDownloadService/DownloadProductResponse")]
        System.IO.Stream DownloadProduct(int idProduct, int idUser, string path, long startPoin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadService/DownloadProduct", ReplyAction="http://tempuri.org/IDownloadService/DownloadProductResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadProductAsync(int idProduct, int idUser, string path, long startPoin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadService/GetFileSize", ReplyAction="http://tempuri.org/IDownloadService/GetFileSizeResponse")]
        long GetFileSize(int idProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadService/GetFileSize", ReplyAction="http://tempuri.org/IDownloadService/GetFileSizeResponse")]
        System.Threading.Tasks.Task<long> GetFileSizeAsync(int idProduct);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDownloadServiceChannel : Client.Service.IDownloadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DownloadServiceClient : System.ServiceModel.ClientBase<Client.Service.IDownloadService>, Client.Service.IDownloadService {
        
        public DownloadServiceClient() {
        }
        
        public DownloadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DownloadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownloadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownloadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream DownloadProduct(int idProduct, int idUser, string path, long startPoin) {
            return base.Channel.DownloadProduct(idProduct, idUser, path, startPoin);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadProductAsync(int idProduct, int idUser, string path, long startPoin) {
            return base.Channel.DownloadProductAsync(idProduct, idUser, path, startPoin);
        }
        
        public long GetFileSize(int idProduct) {
            return base.Channel.GetFileSize(idProduct);
        }
        
        public System.Threading.Tasks.Task<long> GetFileSizeAsync(int idProduct) {
            return base.Channel.GetFileSizeAsync(idProduct);
        }
    }
}
